In [1]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [3]:
import tensorflow as tf
hello = tf.constant('Hello. TensorFlow!')
print(hello)

tf.Tensor(b'Hello. TensorFlow!', shape=(), dtype=string)


In [5]:
import tensorflow as tf

tensor_a = tf.constant(3, name = 'a')
tensor_b = tf.constant(2, name = 'b')
tensor_c = tf.constant(1, name = 'c')

tensor_d = tensor_a * tensor_b
tensor_e = tensor_d + tensor_c

print(tensor_e)
print("{}".format(tensor_e))

tf.Tensor(7, shape=(), dtype=int32)
7


In [12]:
import tensorflow as tf

c = [1, 2, 3, 4, 5]
print(c, type(c))

c_tensor = tf.constant(c)
print(c_tensor, type(c_tensor))
print(c_tensor.numpy())
print(type(c_tensor.numpy()))

[1, 2, 3, 4, 5] <class 'list'>
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import tensorflow as tf
const_s1 = tf.constant(1)
const_v1 = tf.constant([1, 2])
const_v2 = tf.constant([1, 2, 3])
const_m1 = tf.constant([[1, 2, 3], [4, 5, 6]])
const_m2 = tf.constant([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
const_m3 = tf.constant([[[1],[2]], [[3], [4]], [[5], [6]], [[7],[8]], [[9], [10]]])
const_m4 = tf.constant([[[1], [2], [3]], [[4], [5], [6]], [[7], [8], [9]]])

print(tf.rank(const_s1), const_s1)
print(tf.rank(const_v1), const_v1)
print(tf.rank(const_v2), const_v2)
print(tf.rank(const_m1), const_m1)
print(tf.rank(const_m2), const_m2)
print(tf.rank(const_m3), const_m3)
print(tf.rank(const_m4), const_m4)

In [ ]:
import tensorflow as tf

mean, std = 0, 1
print(tf.random.uniform((2, 3), seed = 0))
print(tf.random.normal((2, 3), meam, std))
print(tf.random.truncated_normal((2, 3), mean, std))


In [15]:
import tensorflow as tf

var = tf.Variable(tf.zeros((2, 3)))
print(var)
print(tf.zeros([1, 2, 3]))

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 2, 3), dtype=float32)
