In [1]:
import tensorflow as tf

var = tf.Variable(3)
print(var)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>


In [2]:
import tensorflow as tf

var = tf.Variable(tf.zeros((2, 3)))

print(var)
print(tf.zeros([1, 2, 3]))

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 2, 3), dtype=float32)


In [4]:
import tensorflow as tf
import numpy as np

a = np.ones((2, 3), dtype=np.float32)
b = tf.ones([3, 1], dtype=tf.float32)
print(tf.matmul(a,b))

tf.Tensor(
[[3.]
 [3.]], shape=(2, 1), dtype=float32)


In [5]:
import tensorflow as tf
import numpy as np

var = tf.Variable(tf.ones((2, 3)))
print(var)
var1 = var + 2
print(var1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>
tf.Tensor(
[[3. 3. 3.]
 [3. 3. 3.]], shape=(2, 3), dtype=float32)


In [6]:
import tensorflow as tf

W = tf.Variable(tf.random.normal((3, 2)))
b = tf.Variable(tf.random.normal((2, 1)))

print(W)
print(b)
print(tf.matmul(W,b))

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[-1.0928183,  1.0877666],
       [-1.348303 ,  0.7451274],
       [ 1.3125032, -0.6202949]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-0.26310256],
       [-0.20207097]], dtype=float32)>
tf.Tensor(
[[ 0.06771721]
 [ 0.20417336]
 [-0.21997938]], shape=(3, 1), dtype=float32)


In [10]:
import tensorflow as tf
a = tf.add(3, 5)
print(a)

a = tf.pow(3, 2)
print(a)

a = tf.negative(9)
print(a)

a = tf.divide(9.3,0.3)
print(a)

a = tf.subtract(3.4, 10.2)
print(a)

a =tf.add(3, 3.2)
print(a)

tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(-9, shape=(), dtype=int32)
tf.Tensor(31.0, shape=(), dtype=float32)
tf.Tensor(-6.7999997, shape=(), dtype=float32)


InvalidArgumentError: ignored

In [11]:
import tensorflow as tf

x = tf.constant([0.9, 2.6, 2.3, 1.5, -4.5])
a = tf.round(x)
b = tf.floor(x)
print(a)
print(b)
print(tf.maximum(a,b))
print(tf.cumsum(a, axis=0))
print(tf.math.cumprod(b, axis=0))

tf.Tensor([ 1.  3.  2.  2. -4.], shape=(5,), dtype=float32)
tf.Tensor([ 0.  2.  2.  1. -5.], shape=(5,), dtype=float32)
tf.Tensor([ 1.  3.  2.  2. -4.], shape=(5,), dtype=float32)
tf.Tensor([1. 4. 6. 8. 4.], shape=(5,), dtype=float32)
tf.Tensor([ 0.  0.  0.  0. -0.], shape=(5,), dtype=float32)


In [12]:
import tensorflow as tf

x = tf.constant([[True, True], [False, False]])
print(tf.reduce_any(x))
print(tf.reduce_any(x, 0))
print(tf.reduce_any(x, 1))

print(tf.reduce_all(x))
print(tf.reduce_all(x, 0))
print(tf.reduce_all(x, 1))

y = tf.constant([[1., 1.], [2., 2.]])
print(tf.reduce_mean(y))
print(tf.reduce_mean(y, 0))

print(tf.reduce_mean(y, 1))

t = tf.constant([[1, 2, 3], [1, 1, 1]])
print(tf.reduce_sum(t))
print(tf.reduce_sum(t, 0))
print(tf.reduce_sum(t, 1))

tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor([ True  True], shape=(2,), dtype=bool)
tf.Tensor([ True False], shape=(2,), dtype=bool)
tf.Tensor(False, shape=(), dtype=bool)
tf.Tensor([False False], shape=(2,), dtype=bool)
tf.Tensor([ True False], shape=(2,), dtype=bool)
tf.Tensor(1.5, shape=(), dtype=float32)
tf.Tensor([1.5 1.5], shape=(2,), dtype=float32)
tf.Tensor([1. 2.], shape=(2,), dtype=float32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor([2 3 4], shape=(3,), dtype=int32)
tf.Tensor([6 3], shape=(2,), dtype=int32)


In [14]:
import tensorflow as tf

a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
b = tf.constant([[1, 1], [1, 1]], dtype=tf.float32)
print(tf.matmul(a, b))
print(tf.multiply(a,b))
print(a*b)
print()

print(tf.linalg.inv(a))
print()

t = [[1, 2, 3], [4, 5, 6]]
print(tf.reshape(t, [3, 2]))
print()

x = tf.constant([[1, 2, 3], [4, 5, 6]])
print(tf.transpose(x))
print()

y = tf.expand_dims(x,0)
print(y)
y1 = tf.expand_dims(y,3)
print(y1)
print()

z = tf.squeeze(y1)
print(z)

tf.Tensor(
[[2. 2.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)

tf.Tensor(
[[0.5 0. ]
 [0.  1. ]], shape=(2, 2), dtype=float32)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)
tf.Tensor(
[[[[1]
   [2]
   [3]]

  [[4]
   [5]
   [6]]]], shape=(1, 2, 3, 1), dtype=int32)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [15]:
import tensorflow as tf

X = [[1, 2, 3]]

W = tf.Variable(tf.random.normal([3, 1], dtype=tf.float32), name="W")
b = tf.Variable(tf.random.normal([1, 1], dtype=tf.float32), name="b")

Y = tf.matmul(X, W) + b
print("=== X ===")
print(X)
print("=== W ===")
print(W)
print("=== b ===")
print(b)
print("=== Y ===")
print(Y)

InvalidArgumentError: ignored