In [6]:
import tensorflow as tf

c = [1, 2, 3, 4, 5]

print(c, type(c))
c_tensor = tf.constant(c)
print(c_tensor, type(c_tensor))
print(tf.rank(c_tensor))

[1, 2, 3, 4, 5] <class 'list'>
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(1, shape=(), dtype=int32)


In [8]:
import tensorflow as tf

var = tf.Variable(tf.ones((2, 3)))
print(var)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>


In [9]:
import tensorflow as tf
import numpy as np

a = np.ones((2, 3), dtype=np.float32) # (2.3)의 numpy 배열 생성, 1로 초기화
b = tf.ones([3, 1], dtype=tf.float32) # [3,1] 리스트를 1로 초기화 하여 상수형 텐서 생성

print(tf.matmul(a, b)) # numpy 배열을 텐서로 자동형변환 후 곱 연산 후 텐서로 출력

tf.Tensor(
[[3.]
 [3.]], shape=(2, 1), dtype=float32)


In [10]:
import tensorflow as tf
var = tf.Variable(tf.ones((2, 3))) # 배열 상수형 텐서를 변수형 텐서로 변환
print(var)*
var1 = var + 2 # var은 tf.Tensor로 자동 형변환이 일어나 상수 2와 연산되어 텐서 var1에 저장된다.

print(var1)



<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>
tf.Tensor(
[[3. 3. 3.]
 [3. 3. 3.]], shape=(2, 3), dtype=float32)


In [15]:
import tensorflow as tf

w = tf.Variable(tf.random.normal((3,2)))
b = tf.Variable(tf.random.normal((2,1)))
# 다음과 같이 변수형 텐서에 직접 값을 넣어줄 수도 있다.

# W = tf.Variable([[0.1,0.1],[0.2,0.2], [0.3,0.3]])

print(w)
print(b)

print(tf.matmul(w,b))

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[-2.0869715 , -1.3664387 ],
       [-0.0245794 , -0.00336245],
       [ 0.01361531, -0.7306141 ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-0.63668793],
       [ 0.19089085]], dtype=float32)>
tf.Tensor(
[[ 1.0679089 ]
 [ 0.01500755]
 [-0.14813626]], shape=(3, 1), dtype=float32)


In [17]:
import tensorflow as tf

v1 = tf.Variable(2, name="V-1")
print(v1.name)

v2 = tf.Variable(1)
print(v2.name)

V-1:0
Variable:0


In [25]:
import tensorflow as tf

a = tf.range(10, delta=2, dtype=tf.int32) # 0부터 9까지 2씩 건너뛴 벡터 텐서
print(a)
b = 3 * tf.ones(5, dtype=tf.int32) # 1로 구성된 벡터 텐서
print(b)

print(tf.add(a,b))
print(a+b)

print(tf.multiply(a,b))
print(a*b)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)
tf.Tensor([3 3 3 3 3], shape=(5,), dtype=int32)
tf.Tensor([ 3  5  7  9 11], shape=(5,), dtype=int32)
tf.Tensor([ 3  5  7  9 11], shape=(5,), dtype=int32)
tf.Tensor([ 0  6 12 18 24], shape=(5,), dtype=int32)
tf.Tensor([ 0  6 12 18 24], shape=(5,), dtype=int32)


In [29]:
import tensorflow as tf

x = tf.constant([0.9, 2.6, 2.3, 1.5, -4.5])
a = tf.round(x) # 반올림
b = tf.floor(x) # 버림

print(a)
print(b)
print(tf.maximum(a,b)) # 두 벡터를 비교해서 각 요소별 최대값
print(tf.cumsum(a, axis=0)) # 벡터 a의 요소 값들을 행 기준(axis=0) 으로 누적합
print(tf.math.cumprod(b, axis=0))


tf.Tensor([ 1.  3.  2.  2. -4.], shape=(5,), dtype=float32)
tf.Tensor([ 0.  2.  2.  1. -5.], shape=(5,), dtype=float32)
tf.Tensor([ 1.  3.  2.  2. -4.], shape=(5,), dtype=float32)
tf.Tensor([1. 4. 6. 8. 4.], shape=(5,), dtype=float32)
