In [4]:
import numpy as np
import tensorflow as tf
import matplotlib.pylab as plt
from tensorflow import keras



(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data()


# CNN 입력
train_images = train_images.reshape((60000, 28, 28, 1))
test_images = test_images.reshape((10000, 28, 28, 1))
train_images, test_images = train_images / 255.0, test_images / 255.0

from tensorflow.keras.utils import to_categorical

one_hot_train_labels = to_categorical(train_labels, 10)
one_hot_test_labels = to_categorical(test_labels, 10)
print(one_hot_train_labels[:10])


# (1) Convolution layeer
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv2D(32, (3, 3), activation='relu', strides=(1, 1), input_shape=(28, 28, 1)))

# (2) Max-pooling layer
model.add(tf.keras.layers.MaxPooling2D((2, 2)))

# (3) Convolution layeer
model.add(tf.keras.layers.Conv2D(64, (3, 3), activation='relu'))

# (4) Max-pooling layer
model.add(tf.keras.layers.MaxPooling2D((2, 2)))

# (5) Convolution layeer
model.add(tf.keras.layers.Conv2D(64, (3, 3), activation='relu'))

# (6) Flatten & FC layer (Dense layer)
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(64, activation='relu'))

# (7) FC layer (Dense layer)
model.add(tf.keras.layers.Dense(10, activation='softmax'))

# 모델 학습과정 설정
model.compile(optimizer=tf.optimizers.Adam(learning_rate=0.01), loss='categorical_crossentropy', metrics=['accuracy'])

# 모델 구조 요약 출력
model.summary()

# 모델 학습
history = model.fit(train_images, one_hot_train_labels, epochs=5, batch_size=10)

# 모델 평가 및 결과 출력
labels = model.predict(test_images)
print("\n Accuracy: %.4f" % (model.evaluate(test_images, one_hot_test_labels, verbose=2)[1]))

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d_4 (MaxPoolin  (None, 13, 13, 32)        0         
 g2D)                                                            
                                                                 
 conv2d_7 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_5 (MaxPoolin  (None, 5, 5, 64)        