In [10]:
import numpy as np
import tensorflow as tf
import matplotlib.pylab as plt
from tensorflow import keras
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dense, LSTM, Reshape
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Sequential



# cifar10 데이터셋을 로드하여 준
(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.cifar10.load_data()


# 픽셀값 0~1로 정규화
train_images = train_images.reshape((50000, 32, 32, 3))
test_images = test_images.reshape((10000, 32, 32, 3))
train_images, test_images = train_images / 255.0, test_images / 255.0



# 데이터 레이블 one hot 코드 변경
one_hot_train_labels = to_categorical(train_labels, 10)
one_hot_test_labels = to_categorical(test_labels, 10)
print(one_hot_train_labels[:10])



# (1) Convolution layeer
model = Sequential()
model.add(tf.keras.layers.Conv2D(32, (3, 3), activation='relu', strides=(1, 1), input_shape=(32, 32, 3)))

# (2) Max-pooling layer
model.add(tf.keras.layers.MaxPooling2D((2, 2)))

# (3) Convolution layeer
model.add(tf.keras.layers.Conv2D(16, (3, 3), activation='relu'))

#===========CNN 출력은 13x13크기의 특징맵 16개==============


# Flatten 레이어 추가
model.add(tf.keras.layers.Flatten())

# LSTM 레이어 이전에 Flatten 레이어를 추가한 후의 모델 구조
model.add(Reshape(target_shape=(32, 32, 3)))  # 입력 데이터의 차원 조정
model.add(LSTM(30, return_sequences=False))
model.add(Dense(10, activation='softmax'))






# 모델 학습과정 설정
model.compile(optimizer=Adam(learning_rate=0.01), loss='categorical_crossentropy', metrics=['accuracy'])

# 모델 구조 요약 출력
model.summary()

# 모델 학습
history = model.fit(train_images, one_hot_train_labels, epochs=5, batch_size=32)
print("\n====================test result=====================")
labels=model.predict(test_images)
print("\n Accuracy: %.4f" % (model.evaluate(test_images, one_hot_test_labels)[1]))
print("======================================================")







[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


ValueError: ignored